version: "1.0"
services:
  node:
    build: .
    ports:
      - 9001:9001
    volumes:
      - c8413:/caller8413bot
    networks:
      - c8413
volumes:
  c8413:
networks:
  c8413:
    external: true
    driver: bridge
